"""Static command routing; importing this registry starts no workflows."""

COMMANDS = (
    ('hand', 'align', 'hand_align', 'teleoperation.apps.hand:align'),
    ('hand', 'train', 'hand_train', 'teleoperation.apps.training:run'),
    ('hand', 'export', 'hand_export', 'teleoperation.apps.hand:export'),
    ('hand', 'inspect', 'hand_inspect', 'teleoperation.apps.hand:inspect'),
    ('hand', 'realtime', 'hand_realtime', 'teleoperation.apps.hand:realtime'),
    ('hand', 'record-world', 'hand_record_world', 'teleoperation.apps.world_landmark_capture:main'),
    ('sim', 'run', 'sim_run', 'teleoperation.apps.benchmark:main'),
    ('sim', 'demo-joints', 'sim_demo_joints', 'teleoperation.apps.demo.joints:main'),
    ('dual', 'export', 'dual_export', 'teleoperation.apps.dual_export_cli:main'),
    ('dual', 'realtime', 'dual_realtime', 'teleoperation.apps.dual_realtime:main'),
    ('dual', 'replay', 'dual_replay', 'teleoperation.apps.dual_replay:main'),
    ('replay', 'actions', 'replay_actions', 'teleoperation.apps.replay.replay_actions:main'),
    ('replay', 'native-hand', 'replay_native_hand', 'teleoperation.apps.replay.replay_hand_native:main'),
    ('replay', 'l21-hand', 'replay_l21_hand', 'teleoperation.apps.replay.replay_hand_angles:main'),
    ('replay', 'mounted-hand', 'replay_mounted_hand', 'teleoperation.apps.replay.replay_hand_on_robot:main'),
    ('tools', 'show-robots', 'tools_show_robots', 'teleoperation.apps.diagnostics.show_robots:main'),
    ('tools', 'show-hand', 'tools_show_hand', 'teleoperation.apps.diagnostics.show_hand:main'),
    ('tools', 'check-environment', 'tools_check_environment', 'teleoperation.apps.diagnostics.check_environment:main'),
    ('tools', 'check-camera', 'tools_check_camera', 'teleoperation.apps.diagnostics.check_camera:main'),
    ('tools', 'check-gbk-safe', 'tools_check_gbk_safe', 'teleoperation.apps.diagnostics.check_gbk_safe:main'),
    ('tools', 'compare-training-hand-pose', 'tools_compare_training_hand_pose', 'teleoperation.apps.diagnostics.compare_training_hand_pose:main'),
    ('tools', 'diagnose-hand-coordinates', 'tools_diagnose_hand_coordinates', 'teleoperation.apps.diagnostics.diagnose_hand_coordinates:main'),
    ('tools', 'make-sample-data', 'tools_make_sample_data', 'teleoperation.apps.diagnostics.make_sample_data:main'),
    ('tools', 'show-all-hands', 'tools_show_all_hands', 'teleoperation.apps.diagnostics.show_hands_all:main'),
    ('tools', 'validate-retarget-input', 'tools_validate_retarget_input', 'teleoperation.apps.diagnostics.validate_retarget_input:main'),
    ('tools', 'verify-hand-pipeline', 'tools_verify_hand_pipeline', 'teleoperation.apps.diagnostics.verify_hand_pipeline:main'),
    ('tools', 'verify-p0', 'tools_verify_p0', 'teleoperation.apps.diagnostics.verify_p0:main'),
    ('tools', 'visualize-hand-keypoints', 'tools_visualize_hand_keypoints', 'teleoperation.apps.diagnostics.visualize_hand_keypoints:main'),
    ('tools', 'visualize-l21-fk', 'tools_visualize_l21_fk', 'teleoperation.apps.diagnostics.visualize_l21_fk:main'),
)
