

HAND25_POINTS = 25
TEMPORAL_WINDOW = 3
HAND_ANGLE_DIM = 18
HAND_DOF = 17
FK_FIXED_TIPS = 5
HAND_COORDINATE_DIM = 3
HAND_SIDES = ("left", "right")
ARM_SIDES = HAND_SIDES
RECEPTIVE_FIELD = TEMPORAL_WINDOW
HAND_KEYPOINTS = HAND25_POINTS
HAND_COORDS = HAND_COORDINATE_DIM

DEFAULT_MAX_CENTER_DISPLACEMENT = 0.08
DEFAULT_MAX_SHAPE_RMSE = 0.05
